[project]
name = "dotfiles"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"
authors = ["Alexander Ivanov <alexander.valentinov.ivanov@gmail.com>"]

[tasks]

[dependencies]
python = ">=3.10"
pre-commit = "*"
